### ISSUE TITLE
Ditto v0.7.0 released

### ISSUE THREAD

**Issue by leekelleher** [micklaw/Ditto.Resolvers#1]
Hey @micklaw, Ditto v0.7.0 has been released, so you can reference the NuGet package now :sunglasses:

**Comment by micklaw** [comment]
@leekelleher Awesome!!!

I noticed on Twitter, I'll get cracking and fire up a Nuget package. Think I'll seperate out the resolvers to seperate assemblies while I'm at it.

Battling Tonsillitis currently, so might take a wee day or too.

Nice work on the new release!!

**Comment by leekelleher** [comment]
Aw man, hope you feel better soon!

**Comment by micklaw** [comment]
Closed as using the master branch now.
