### ISSUE TITLE
Doesn't Work with Ditto Conversion Handlers

### ISSUE THREAD

**Issue by Nicholas-Westby** [micklaw/Ditto.Resolvers#10]
I have some code that looks like this:

```cs
// Namespaces.
using Our.Umbraco.Ditto.Resolvers.Archetype.Attributes;
using System.Collections.Generic;
using System.ComponentModel;
using Converters;
using Types;
using Our.Umbraco.Ditto;


/// <summary>
/// An article gallery widget.
/// </summary>
[ArchetypeContent(alias: "articleGalleryTagged")]
public class ArticleGalleryTagged : IWidget, IArticleGallery
{

    #region Properties

    /// <summary>
    /// A article gallery widget.
    /// </summary>
    public string Header { get; set; }


    /// <summary>
    /// The gallery summary.
    /// </summary>
    public string Summary { get; set; }


    /// <summary>
    /// The gallery link.
    /// </summary>
    [TypeConverter(typeof(LinkConverter))]
    public Link Link { get; set; }


    /// <summary>
    /// The articles.
    /// </summary>
    public List<ArticleCard> Articles { get; set; }

    #endregion


    //TODO: ...
    [DittoOnConverting]
    internal void OnConverting(DittoConversionHandlerContext context)
    {
        var x = context;
    }


    //TODO: ...
    [DittoOnConverted]
    internal void OnConverted(DittoConversionHandlerContext context)
    {
        var x = context;
    }

}
```

Since the articles in this widget are populated based on a couple of other properties in the Archetype (in particular "tags" and "matchAllTags"), my hope was that I could use a ditto conversion handler to populate the articles based on the conversion handler context. However, I set breakpoints on both of the lines that say `var x = context;` and those breakpoints were never hit.

I tried the `DittoOnConverting` and `DittoOnConverted` attributes at a higher level (where I am mapping using Ditto proper rather than Ditto Resolvers) and the breakpoints were hit.

My hope is that you could find some way to get these attributes functioning in a Ditto Resolvers context.

**Comment by micklaw** [comment]
That's an interesting idea. 

For me it's all about simply binding, but think it would be nice to have this feature. I'll have a go at hooking to the Ditto events, if not I'll roll my own, to achieve something similar.

Thinking about it, I think I might jus my so my own anyway, as I fear there maybe more reflection required here.

**Comment by micklaw** [comment]
Was nice and easy to add support for these two attributes. Give this a whack, should fire for each fieldset when binded.

[Ditto.Resolvers.Archetype.1.0.3-alpha-000126.zip](https://github.com/micklaw/Ditto.Resolvers/files/104941/Ditto.Resolvers.Archetype.1.0.3-alpha-000126.zip)

You should be able to extract the files from this, or change its name to nupkg and installl from your feed.

**Comment by micklaw** [comment]
Hey @Nicholas-Westby,

I have added the ArchetypeFieldsetModel to the context now. I've uploaded it here for you to try.

I events at the class level using the Ditto Attributes, but also added property level Attributes too. Check the description (ReadMe.MD) on the dev branch and you can see how to use them.

Cheers

[Ditto.Resolvers.Archetype.1.0.3-alpha-000128.zip](https://github.com/micklaw/Ditto.Resolvers/files/108609/Ditto.Resolvers.Archetype.1.0.3-alpha-000128.zip)

**Comment by Nicholas-Westby** [comment]
@micklaw This did not seem to work. I added some breakpoints in my functions (`OnConverting` and `OnConverted`) and my breakpoints were never hit. Here's the file I just tested this with:

```cs
// Namespaces.
using Converters;
using Converters.Bool;
using Our.Umbraco.Ditto;
using Our.Umbraco.Ditto.Resolvers.Archetype.Attributes;
using System.Collections.Generic;
using System.ComponentModel;
using Types;


/// <summary>
/// An article gallery widget.
/// </summary>
[ArchetypeContent(alias: "articleGalleryTagged")]
public class ArticleGalleryTagged : IWidget, IArticleGallery
{

    #region Properties

    /// <summary>
    /// The gallery header.
    /// </summary>
    public string Header { get; set; }


    /// <summary>
    /// The gallery summary.
    /// </summary>
    public string Summary { get; set; }


    /// <summary>
    /// The gallery link.
    /// </summary>
    [TypeConverter(typeof(LinkConverter))]
    public Link Link { get; set; }


    /// <summary>
    /// The articles.
    /// </summary>
    public List<ArticleCard> Articles { get; set; }


    /// <summary>
    /// The tags to use when finding articles.
    /// </summary>
    [TypeConverter(typeof(TagsConverter))]
    public List<string> Tags { get; set; }


    /// <summary>
    /// Match articles that contain all of the tags or any of the tags?
    /// </summary>
    [TypeConverter(typeof(ConfigurableBoolConverter<DefaultFalse>))]
    public bool MatchAllTags { get; set; }

    #endregion


    //TODO: ...
    [DittoOnConverting]
    internal void OnConverting(DittoConversionHandlerContext context)
    {
        var x = context;
    }


    //TODO: ...
    [DittoOnConverted]
    internal void OnConverted(DittoConversionHandlerContext context)
    {
        var x = context;
    }

}
```

Here are my breakpoints:

![breakpoints](https://cloud.githubusercontent.com/assets/5933222/12727656/b83e4a1e-c8d2-11e5-8886-490a0eafdd78.png)

I tested it with the latest version you linked (i.e., `Ditto.Resolvers.Archetype.1.0.3-alpha-000128.zip`).

**Comment by micklaw** [comment]
Hey man,

Think your missing the extra param on your method signature:

private void InvokeConvert(MethodInfo method, object instance, DittoConversionHandlerContext context, ArchetypeFieldsetModel fieldset)
        {
            var p = method.GetParameters();

            if (p.Length == 2 && p[0].ParameterType == typeof(DittoConversionHandlerContext) && p[1].ParameterType == typeof(ArchetypeFieldsetModel))
            {
                method.Invoke(instance, new object[] { context, fieldset });
            }
        }

As you can see from the method above, the method signature for the conversion handlers require you to have a parameter for the ArchetypeFieldsetModel now too.

Cheers

**Comment by Nicholas-Westby** [comment]
@micklaw Didn't seem to work. My breakpoints still aren't being hit:

```cs
//TODO: ...
[DittoOnConverting]
internal void OnConverting(DittoConversionHandlerContext context, ArchetypeFieldsetModel model)
{
    var x = context;
}

//TODO: ...
[DittoOnConverted]
internal void OnConverted(DittoConversionHandlerContext context, ArchetypeFieldsetModel model)
{
    var x = context;
}
```

**Comment by micklaw** [comment]
@Nicholas-Westby,

Man, in adding the property level events I broke the class level events. That's it sorted now.

*Must add unit tests for events.

[Ditto.Resolvers.Archetype.1.0.3-alpha-000129.zip](https://github.com/micklaw/Ditto.Resolvers/files/114813/Ditto.Resolvers.Archetype.1.0.3-alpha-000129.zip)

**Comment by Nicholas-Westby** [comment]
@micklaw Seems to be working!

**Comment by micklaw** [comment]
Awesome, I'll close this now and do a full release tomorrow.

**Comment by Nicholas-Westby** [comment]
@micklaw Looking forward to the release when you get a chance :-)

**Comment by Nicholas-Westby** [comment]
FYI, this isn't working. It worked with 1.0.3-alpha-000129, but it is not working with 1.0.4. I tried it in 1.0.4, which didn't work (breakpoint was never hit), then I reverted to 1.0.3-alpha-000129, which worked. Then I changed back to 1.0.4 and it again didn't work. Here's my code:

```cs
// Namespaces.
using Archetype.Models;
using Converters;
using Converters.Bool;
using Helpers;
using Our.Umbraco.Ditto;
using Our.Umbraco.Ditto.Resolvers.Archetype.Attributes;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using Types;


/// <summary>
/// An article gallery widget.
/// </summary>
[ArchetypeContent(alias: "articleGalleryTagged")]
public class ArticleGalleryTagged : IWidget, IArticleGallery
{

    #region Properties

    /// <summary>
    /// The gallery header.
    /// </summary>
    public string Header { get; set; }


    /// <summary>
    /// The gallery summary.
    /// </summary>
    public string Summary { get; set; }


    /// <summary>
    /// The gallery link.
    /// </summary>
    [TypeConverter(typeof(LinkConverter))]
    public Link Link { get; set; }


    /// <summary>
    /// The articles.
    /// </summary>
    public List<ArticleCard> Articles { get; set; }


    /// <summary>
    /// The tags to use when finding articles.
    /// </summary>
    [TypeConverter(typeof(TagsConverter))]
    public List<string> Tags { get; set; }


    /// <summary>
    /// Match articles that contain all of the tags or any of the tags?
    /// </summary>
    [TypeConverter(typeof(ConfigurableBoolConverter<DefaultFalse>))]
    public bool MatchAllTags { get; set; }

    #endregion


    #region Ditto Mapping Methods

    /// <summary>
    /// Sets the articles based on the selected tags.
    /// </summary>
    /// <param name="context">
    /// The conversion context.
    /// </param>
    /// <param name="model">
    /// The Archetype fieldset for the widget.
    /// </param>
    [DittoOnConverted]
    internal void OnConverted(DittoConversionHandlerContext context, ArchetypeFieldsetModel model)
    {
        Articles = PublicationHelper
            .GetArticlesByTags(5, MatchAllTags, Tags.ToArray())
            .Select(x => new ArticleCard()
            {
                Categories = x.Categories,
                Image = PublicationHelper.GetPublicationImage(x.Content, "Article"),
                Link = x.Link
            }).ToList();
    }

    #endregion

}
```

**Comment by micklaw** [comment]
Pushed 1.0.5 now which has the correct code in it this time :)
