### ISSUE TITLE
Doctype Properties Overriding Archetype Properties

### ISSUE THREAD

**Issue by Nicholas-Westby** [micklaw/Ditto.Resolvers#13]
I have a model that looks like this:

```cs
[ArchetypeContent(alias: "linkSidebarCallout")]
public class LinkSidebarCallout : IWidget
{

    [ArchetypeProperty(alias: "header")]
    public string Header { get; set; }

    public string Summary { get; set; }

    [TypeConverter(typeof(LinkConverter))]
    public Link Link { get; set; }

}
```

The `header` is a property on the Archetype fieldset. However, `header` is also a property on the page in which the Archetype property exists. What seems to be happening is that my `Header` C# property is getting populated with the value of the document type `header` property rather than the Archetype `header` property (FYI, the other two properties, `Summary` and  `Link`, are populating fine).

Note that I added an OnConverting function to inspect all the values and my theory seems to hold true (i.e., the Archetype model contains the correct header, but the `Header` property is getting the wrong value). Also, I added the `ArchetypeProperty` attribute in an attempt to let Ditto Resolvers know I was in fact looking for an Archetype property, but it didn't change anything.

**Comment by Nicholas-Westby** [comment]
Here's an example of the page this is on:

![stuff](https://cloud.githubusercontent.com/assets/5933222/13129613/e82b84b8-d592-11e5-83ee-e631bba89f8e.png)

I get a header populated with the value "Stuff" (I would expect it to be "Things").

**Comment by micklaw** [comment]
[Ditto.Resolvers.Archetype.1.0.7-alpha-000144.zip](https://github.com/micklaw/Ditto.Resolvers/files/136958/Ditto.Resolvers.Archetype.1.0.7-alpha-000144.zip)

Give this a whack Nicholas. 

Ditto tries the resolver conversion, then the output of that goes to the type converter. Ditto matches the 'Header' value on the Doc Type, and so therefore doesnt use the Archetype property. I now attempt to use the archetype property first, and if null then does the Ditto check. I think it should sort it.

**Comment by Nicholas-Westby** [comment]
That seems to fix it!

**Comment by Nicholas-Westby** [comment]
Sorry to be a pest, but is there any chance this will be released soon? Thanks!

**Comment by micklaw** [comment]
Sorry, life getting in the way as usual. I'll endeavour to release tonight

**Comment by micklaw** [comment]
https://github.com/micklaw/Ditto.Resolvers/releases/tag/1.0.7

**Comment by Nicholas-Westby** [comment]
Yay! Thanks!

**Comment by micklaw** [comment]
Ha. Again, apologies it took so long.
