### ISSUE TITLE
Support for Ditto 0.9.0?

### ISSUE THREAD

**Issue by Nicholas-Westby** [micklaw/Ditto.Resolvers#14]
Just curious if this will support the new Ditto 0.9.0 release (currently in beta): https://github.com/leekelleher/umbraco-ditto/releases/tag/0.9.0-beta

**Comment by micklaw** [comment]
Hey Nicholas,

I haven't really looked at the new Ditto beta release. I vaguely remember having a discussion on here when @mattbrailsford was working on the processor stuff which seemed like a logical move for the framework.

It looks from the release note that there a few breaking changes, but nothing major to change from my end I wouldn't think at first glance. I've been away from Umbraco for a good 6 months now, but hopefully won't take too long to get my mind back in to it.

So I'll stop rambling on and say yes, thiugh I couldn't give an exact ETA on when. Are you thinking of making the move to the beta release quickly?

Cheers

**Comment by Nicholas-Westby** [comment]
I'm considering it, but I'm not sure I have time for it. What I'm seeing is that my pages are taking at least a half second to render (time to first byte). I can't be certain that's Ditto, but all my pages are doing is essentially calling Ditto to map things and then rendering those things, so it seems likely that the bottleneck could be Ditto. Since Ditto has some performance enhancements in this release, I'm considering upgrading to see if it helps the issues I've been seeing (i.e., the half second load time).

**Comment by micklaw** [comment]
Yeah, I don't think I'd be blaming Ditto for that in fairness, unless you are binding lots of stuff, or having lots of events etc fired when thing are being bound.

i went through a phase in Umbraco using Ditto for a lot of fairly meaty websites and some of them has very large nodes, performance was never an issue. Half second on the server seems very slow, generally response times from me ranged from anything between 20-100ms.

Have you tried to output the mini profiler to see what's taking your time or adding some logging?

**Comment by Nicholas-Westby** [comment]
It seems to be death by a thousand cuts:

![profile](https://cloud.githubusercontent.com/assets/5933222/14863655/774a8252-0c6b-11e6-8ad2-0b13559328f7.png)

"MainContent", by the way, is the Umbraco property that is the Archetype that has all my widgets for the page. It actually appears on this list twice (once because I map it in my `Typical.cshtml` and once in my `Primary.cshtml`). I could probably get rid of that double mapping inefficiency by mapping in a controller rather than in the views themselves (because then the mapping would happen once in the controller, and that model would be passed to the views), which would take the total render time to about 250ms.

If this Ditto update further enhances the performance, that total render time may go down to 125ms.

I'm not sure of a good way of adding MVC mini profiler logging with Ditto/Archetype Value Resolvers except for in my type converters and value resolvers (of course, in the new version of Ditto, that would just be in my processors, as type converters and value resolvers are obsolete).

If you are curious, here is my class that contains the `MainContent` property:

```csharp
/// <summary>
/// Typical information for pages.
/// </summary>
public class Typical
{

	#region Variables

	/// <summary>
	/// The main content for this page.
	/// </summary>
	private List<IWidget> mainContent;

	#endregion


	#region Properties

	/// <summary>
	/// The main content for this page.
	/// </summary>
	[ArchetypeValueResolver(alias: "mainContent")]
	public List<IWidget> MainContent
	{
		get
		{
			return mainContent ?? new List<IWidget>();
		}
		set
		{
			mainContent = WidgetHelper.ProcessWidgets(value);
		}
	}

	#endregion

}
```

**Comment by Nicholas-Westby** [comment]
By the way, the slowness I observed seemed to resolve itself somewhat. Pages now tend to take around 250ms to load. I'm still going to try using a controller to halve my calls to the ditto mapping code, but that's looking not so bad anymore. Maybe it was going slow because somebody else was using CPU (it's a shared dev environment at my company).

Would still be nice to have support eventually for the new Ditto, but no rush :-)

**Comment by micklaw** [comment]
Hey @Nicholas-Westby,

I've had a run though the new Ditto source and its not good news I'm afraid. The new version of Ditto doesn't seem to be flexible enough in the way this used to work. The breaking changes would require too large a rewrite of the existing source. I think it would require a ground-up approach.

From what I can see we used to piggy back on a couple of private methods via a reflection, one of which,instead of using the IPublishedContent to extract the propertyto set on our Archetype, used a property value, this method no longer exists,so everything seems to hang from IPublishedContent, we pull values from an ArchetypeFieldSetModel, this would no longer be possible.

There is maybe something we could do with converting an Archetype to an IPublshedContent (sure an extension method for this exists), but personally I don't have the time to invest, especially with being quite far removed from the Umbraco ecosystem currently.

So apologies for that, but time is a precious commodity at the moment. We had a good run while it lasted. But think I will be parking this one now.

Cheers

Michael

**Comment by micklaw** [comment]
I'm just going to close this off now dude.

Cheers

**Comment by Nicholas-Westby** [comment]
Well that's a bummer. I'll chat with the Ditto folks to see if there's anything they can do to make Ditto more extensible. Thanks for all of your help to date. Very much appreciated. #h5yr

**Comment by micklaw** [comment]
It's a good point, I do think under the hood, Ditto could be much more extensible. There are lots of internal classes and static methods,which must make test coverage difficult to keep high,but they are clever guys, so I am sure what ever decisions or patterns they use have good reason.

For me I think the move away from Value Resolvers and Type converters is a good one,but has brought about having to relearn, how the processor stuff hangs internally, as to the outside it doesn't seem like much has changed, in terms of processing a lot has. I reckon figuring this out would be where the time will be spent, if either of us were to fully give it a whack.

Thanks for the nice message, it's not a problem, I've enjoyed working on it!

**Comment by Nicholas-Westby** [comment]
There may be a happy ending after all. Looks like there may be an alternative: https://github.com/leekelleher/umbraco-ditto/issues/167#issuecomment-215932113
