### ISSUE TITLE
Use of ditto logo

### ISSUE THREAD

**Issue by mattbrailsford** [micklaw/Ditto.Resolvers#3]
Hey,

Really appreciate the work you are doing with these resolvers, but could I request that you don't use the Ditto logo for things like the nuget package icon as it makes it look like an official add-on in the nuget feed so could cause confusion.

Many thanks

Matt

**Comment by micklaw** [comment]
Worries, I'll remove it ASAP.

Cheers

**Comment by micklaw** [comment]
Removed from nuget and dev branch. Will be removed from main branch on next release (if there is one =))

**Comment by mattbrailsford** [comment]
Cheers. Appreciate it. Keep up the good work with it.
