### ISSUE TITLE
More Elegant Support for Multiple Archetype Fieldsets

### ISSUE THREAD

**Issue by Nicholas-Westby** [micklaw/Ditto.Resolvers#4]
I was reading that currently I must inherit my class from ArchetypeFieldsetModel if I want to resolve a list of items that come from an Archetype property that contains multiple fieldset types. I'm hoping you can find a way around that, as that is my most common scenario and I'd like to avoid polluting all my models with a base of ArchetypeFieldsetModel.

Basically, I have pages like this:

```
public class InfoPage
{
    public List<IWidget> Widgets { get; set; }
}
```

A number of classes implement `IWidget` (e.g., `RichText`, `Image`, `Callout`, `Slideshow`, and so on).

Is there any plan to support this scenario (i.e., lists of polymorphic items that don't inherit from ArchetypeFieldsetModel)?

**Comment by micklaw** [comment]
Hey Nicholas. 

Currently we need a way to find all instances of Archetype related POCOs so we can ma types to aliases, we do this by inheriting our classes from the ArchetypeFieldsetModel. Doing this also allows us to piggy back on some additional functionality exposed from the Archetype class, but this functionality could easily be abstracted away to an interface or abstract class. 

So if you don't mind using an abstract class or interface on your own POCOs for Archetype Fieldsets then I'm pretty sure I could achieve this easily.

There may be a slight issue with nested Archetypes, but can't be sure till i dig in. Let me know what you think.

**Comment by Nicholas-Westby** [comment]
I'm not familiar with your code base (I'm also new to Ditto itself), but conceptually I don't see why you'd need to have the model inherit from a particular interface or class. Perhaps there is some reason that I'm not aware of, but I'll explain from my perspective how I imagine it should work.

Suppose I have an instance of ArchetypeModel that contains a couple of fieldsets. One may be an `Image` fieldset and one may be a `Callout` fieldset. I would imagine a solution that looks something like this:

```
public class InfoPage
{
    [MapFromArchetypeModel]
    public List<IWidget> Widgets { get; set; }
}
```

Then I'd have a class for the `Image` fieldset:

```
[MapFromArchetypeFieldset(FieldsetAlias = "Image")]
public class Image : IWidget
{
    public string Url { get; set; }
    public string AltText { get; set; }
}
```

Then i'd have a class for the `Callout` fieldset:

```
[MapFromArchetypeFieldset(FieldSetAlias = "Callout")]
public class Callout : IWidget
{
    public string Header { get; set; }
    public string Summary { get; set; }
    public string Url { get; set; }
}
```

I would think I could then do this (say, in a razor partial):

```
var page = Model.Content.As<InfoPage>();
var widgets = page.Widgets;
// ...Loop over widgets and handle them based on the particular instance type...
```

Note that I just made up those attributes. This is how I imagine they would work:
* **MapFromArchetypeModel** Your resolver code would look at that attribute to figure out that the list of widgets should be resolved from an Archetype model. 
* **MapfromArchetypeFieldset** This would inform your resolver code that this class can be used to materialize the Archetype fieldset with the specified alias.

There would be some nuances to consider (e.g., if an "Image" fieldset under a "Slideshow" fieldset maps differently than an "Image" fieldset that has no parent fieldset), but that's the basic idea.

Is there some reason doing that would not work?

**Comment by micklaw** [comment]
Yeah that is 100% achievable. Though, as I say, there is an internal TypeIdentifier class which takes the Archetype Fieldset alias and maps this text value to a Strong Type. It is essentially a ConcurrentDictionary<string, Type>. So when we are iterating across the fieldsets in the json, we know which Strong Type to use, by doing a lookup on this collection with the fieldset alias.

Without some sort of Identification how would i know which classes are your custom Archetypes as it is possible that some POCOs might not have an IWIdget at all? This is why the base class is used now, but as i say we could easily swap this for an abstract class or interface. We could maybe use the attribute, but for me it would be a frustration to have to include this on alll my POCOS.

**Comment by Nicholas-Westby** [comment]
> Without some sort of Identification how would i know which classes are your custom Archetypes as it is possible that some POCOs might not have an IWIdget at all?

In my example, IWidget isn't actually used for anything related to mapping. I could have created a `List<object>` rather than a `List<IWidget>` and I'd imagine it would function exactly the same. You would know which classes to instantiate based on the attributes that map them to Archetype fieldset aliases.

You could use the alias specified in the attributes to populate your ConcurrentDictionary.

> This is why the base class is used now, but as i say we could easily swap this for an abstract class or interface. We could maybe use the attribute, but for me it would be a frustration to have to include this on alll my POCOS.

In my view, attributes are less invasive and more expressive than implementing an interface or inheriting from a base class (e.g., I may want to inherit from another base class from a third party that itself can't inherit from ArchetypeFieldsetModel).

Also, the attributes would only be necessary in parts of the code that require mapping of polymorphic types. That is, if I create a `List<Callout>`, I would not need any attributes, as there are no types derived from `Callout`. Note also that you wouldn't actually need to test if a class is "polymorphic" (i.e., whether or not it has derived types). You would first check for attributes to see if there are particular classes that can be used for particular Archetype fieldset aliases, then you'd just try to instantiate the class itself.

**Comment by micklaw** [comment]
Yeah as I said in the quote you picked, we could use the attributes, not a problem other than slowing down the initial caching of alias to Type mapping. Though I disagree that attributes would not always be needed for all POCOs. For example, how would be we know in the POCO below that this mapped to an "image" fieldset alias, just using class name wouldn't be a working solution?

```csharp
public class Image {
    public string Url { get; set; }
}
```

Also Archetype Fieldsets has some shared properties on mapping e.g. Disabled, Alias etc. This is nice functionality to keep from my side, so an abstract class or interface assists  in sharing this functionality. I agree though that lack of multi inheritance lends me to look for consumers to implement and interface.

**Comment by Nicholas-Westby** [comment]
> how would be we know in the POCO below that this mapped to an "image" fieldset alias, just using class name wouldn't be a working solution

Presumably, you'd have another class that has a property of type `Image`. Let's take this as an example:

```
public class InfoPage
{
    public Image Header { get; set; }
}
```

And let's assume this code to perform the mapping:

```
var page = Model.Content.As<InfoPage>();
var headerUrl = page.Header.Url;
```

Given this example, here are the knowns and assumptions:
* The current page has a property with an alias of "header" and it is storing a value of type ArchetypeModel.
* Your resolver code will handle the mapping of ArchetypeModels.

Without having any extra attributes, your code could see that the `Header` C# property is not `IEnumerable`. Given that the `ArchetypeModel` has a number of fieldsets, your code could assume that you will be mapping the first of those fieldsets into an instance of `Image` (since that is the type of the `Header` property). Your code would see that the `Image` class contains a `Url` property and it would see that the first fieldset contains a property with alias `url`. It could at that point instantiate a new `Image` instance and assign the value of the C# `Url` property based on the value of the `url` Archetype property.

Is there some unknown that I'm not seeing that would not allow for this mapping process to occur as I've described?

> Also Archetype Fieldsets has some shared properties on mapping e.g. Disabled, Alias etc. This is nice functionality to keep from my side, so an abstract class or interface assists in sharing this functionality.

Perhaps you could make the interface optional? That is, if I inherit `Image` from `IArchetypeFieldsetInfo`, then you can set those base properties (e.g., `Disabled` and `Alias`). However, I don't see that it would be necessary to require that interface.

**Comment by micklaw** [comment]
That all sounds like a good approach to me and think the suggestions would make it more flexible. The code does cache a decent amount of information regarding alias to Type mapping and also Type to Property mappings, so if you are going to have a blast at it, that's an area I'd say to watch out for. Most of the other stuff like assigning inherited / abstracted types to the list should be quick to change though.

In honesty, I'd love to have time to do this quickly for you, but fear that current work commitments are going to put pave to any sort of quick turn around. Its also been a while since i looked at this source so I'll need to remind myself how it works again. Sometimes I forget code I wrote last week never mind X months ago.

I'll give it a whack asap and hopefully get something out.

**Comment by Nicholas-Westby** [comment]
No rush. I don't think this is going to work for me for the current project I'm working on, so I've already started down a different road.

I'd love to give it another look when I start working on my next project, however :-)

**Comment by micklaw** [comment]
Nicholas, you got me interested =)

I created another branch and hooked up the stuff you were talking about. So...

Gone is the dependency on ArchetypeFieldsetModel
If using a Multi Fieldset Archetype you need to define and interface or abstract class and implement it with each POCO along with adding a ArchetypeContentAttribute to it too (with optional custom alias)
If you also implement an IFieldset interface then it will hook the Disabled and Alias fields too

I think AppVeyor will hook a nuget deploy up for you soon. Cant remember though, if not ill merge it to dev and give it a go.

Cheers

**Comment by Nicholas-Westby** [comment]
Wow, that was fast! I'll give it a try when I get to work tomorrow. I'll start with the `RichText` widget I'm currently working with. Out of curiosity, does your code allow for something like this:

```
public class RichText : IWidget
{
    [ArchetypeProperty(Alias = "richText")]
    public string Text { get; set; }
}
```

I can't call my property `RichText` because that happens to be the name of my class (I suppose I could just rename my class). I'm thinking there should be an attribute that can guide the mapper in cases like this so it knows which property to grab the value from.

No worries if you don't have time to reply to that question. I'll give it a go tomorrow regardless. Thanks again for the quick turnaround!

**Comment by micklaw** [comment]
Yeah, at this point you can lean on Ditto and use its UmbracoPropertyAttribute I think =)

http://umbraco-ditto.readthedocs.org/en/latest/usage-advanced-attributes/

**Comment by micklaw** [comment]
You should now be able to update to the latest -pre via nuget to get these changes. It is pre though, so beware. I'm going to add some more tests today at some point to make sure it all still works!

**Comment by Nicholas-Westby** [comment]
I'm giving this a try now, but wanted to give you a heads up about an install issue. Looks like your NuGet package has a dependency on the Archetype NuGet package. So, when I install your package into my class library project, I get an `App_Plugins/Archetype` folder with a bunch of stuff in it. That's a bit weird to have in a class library that the website references.

FYI, there is an issue I happened to create recently requesting that a NuGet package for the Archetype binaries be released separately from the main Archetype NuGet package: https://github.com/imulus/Archetype/issues/312

If that gets released, this is the perfect use case for how it could be used.

**Comment by Nicholas-Westby** [comment]
Also, looks like your project is referencing an old version of Archetype (1.7.5). Current version is 1.12.1. Might be worth updating that.

**Comment by Nicholas-Westby** [comment]
It works! Sort of...

Curiously, my list of widgets is empty the first time I load the page. If I refresh, the list of widgets is then populated.

Here's my CSHTML (minus the using statements):

```
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Wrapped.cshtml";
    var page = Model.Content.As<TypicalPage>();
    var widgets = page.MainContent;
}

<h1>This is a Typical Page</h1>
@foreach(var generalWidget in widgets)
{
    if (generalWidget is RichTextWidget)
    {
        var widget = generalWidget as RichTextWidget;
        @Html.Raw(widget.RichText)
    }
}
```

Here's my `TypicalPage` class:

```
/// <summary>
/// The model for a typical page.
/// </summary>
public class TypicalPage
{

    #region Properties

    /// <summary>
    /// The main content for this page.
    /// </summary>
    [ArchetypeValueResolver(alias:"mainContent")]
    public List<IWidget> MainContent { get; set; }

    #endregion

}
```

Here's my `IWidget` class:

```
public interface IWidget
{
}
```

Here's my `RichTextWidget` class:

```
/// <summary>
/// A rich text widget.
/// </summary>
[ArchetypeContent(alias: "RichText")]
public class RichTextWidget : IWidget
{
    public string RichText { get; set; }
}
```

**Comment by Nicholas-Westby** [comment]
FYI, I was unable to use an attribute to specify the Archetype property alias:

```
/// <summary>
/// A rich text widget.
/// </summary>
[ArchetypeContent(alias: "RichText")]
public class RichTextWidget : IWidget
{
    [ArchetypeValueResolver(alias: "richText")]
    [UmbracoProperty(PropertyName =  "richText")]
    public string Text { get; set; }
}
```

I tried those attributes (`ArchetypeValueResolver` and `UmbracoProperty`) individually and I tried them both at the same time. None of those combinations seemed to work.

**Comment by micklaw** [comment]
Ha, cool, cheers for giving it a go. Guarenteed it will be to do with the caching of alias to types or something on first go, the order where I'm checking and creating will be off somewhere. Sure it won't be a big deal to fix. 

I'll try and jump on it later, though with two kids on Xmas eve it may be struggle to get some time =) 

Yeah archetype seems to install this stuff when referenced as a budget package and good shout on updating. I'm sure there will be plenty more improvements it will make use off.

Feel free to fork away if you like and tackle some of the issue you mentioned. Or no worries if you fancy waiting for a wee bit.

**Comment by Nicholas-Westby** [comment]
Yeah, caching was my guess too. I'll just use it as is with the understanding that I'll have to refresh an extra time for now and I'll have to be sure to name my classes to avoid having to specify aliases for properties.

Once you have some time to code some fixes, I'll update and make sure they work. Have a merry Christmas :-)

**Comment by micklaw** [comment]
Nice one.

Shouldn't be to long until I'll sort those. Have a great Christmas too.

**Comment by micklaw** [comment]
Hey Nicholas,

I have fixed the caching issue now and also amended the logic a little to allow the ArchetypeValueResolverAttribute to be used for just its alt alias.

I updated the Archetype version too. When they hook up you issue to include the binaries only, I'll change to this package.

Hope it works out ok for you. If so give me the nod and Ill close this issue.

Thanks again for your suggestions and interest, wasn't actually sure if anyone actually used this bar me!

**Comment by Nicholas-Westby** [comment]
Looks like both issues have been fixed! That is, I see the content on the first page load and I can specify an alias using the `ArchetypeValueResolver` attribute:

```cs
// Namespaces.
using Our.Umbraco.Ditto.Resolvers.Archetype.Attributes;


/// <summary>
/// A rich text widget.
/// </summary>
[ArchetypeContent(alias: "RichText")]
public class RichTextWidget : IWidget
{

    #region Properties

    /// <summary>
    /// The rich text.
    /// </summary>
    [ArchetypeValueResolver(alias:"richText")]
    public string Text { get; set; }

    #endregion

}
```

One thing I will note is that the NuGet package still has a dependency on the old version of Archetype (1.7.5): https://www.nuget.org/packages/Ditto.Resolvers.Archetype/0.2.0-alpha-000068

Doesn't really matter though. I am just uninstalling Archetype with this line in the Package Manager Console:

```
Uninstall-Package Archetype -Force
```

And then I'm referencing the Archetype DLL in a "lib" folder at the root of my solution.

By the way, I'm going to try some more advanced scenarios now (e.g., custom type converters on nested Archetypes), but as far as support of more elegant support of multiple Archetype fieldsets (i.e., this issue), I would definitely consider that done and ready to be closed. Thanks!

**Comment by micklaw** [comment]
Nice one, I left it as 1.75 as technically it will work and does support it, though internally it is referencing the most recent which is maybe a little misleading I agree.

Glad that fixed your issues though.

As for your more advanced usages. Here's hoping it should just work. I've been using this on my own project for a good amount of time and it has always worked well with nested archetypes with custom type converters etc.

Look forward to hearing your results =)

Cheers
