### ISSUE TITLE
TypeConverter Does Not Work with Nested Archetypes

### ISSUE THREAD

**Issue by Nicholas-Westby** [micklaw/Ditto.Resolvers#5]
In short, I have a `Callout` widget that has a `Link` property of type `Link`. I decorated that property with the `TypeConverter` attribute to specify my custom type converter. However, that type converter is not called.

Here's my main class for my page:
```cs
public class TypicalPage
{
    [ArchetypeValueResolver(alias:"mainContent")]
    public List<IWidget> MainContent { get; set; }
}
```

And here's my widget interface (it's just an empty interface):
```cs
public interface IWidget
{
}
```

And here's my `Callout` widget (note the type converter on the `Link` property):
```cs
[ArchetypeContent(alias: "Callout")]
public class Callout : IWidget
{
    public string Header { get; set; }
    public string Summary { get; set; }

    [TypeConverter(typeof(LinkConverter))]
    [ArchetypeValueResolver(alias: "link")]
    public Link Link { get; set; }

}
```

And here's my `Link` class:
```cs
public class Link
{
    public string Title { get; set; }
    public string Url { get; set; }
    public string Label { get; set; }
    public bool NewWindow { get; set; }
}
```

Here's my type converter (it's currently just hardcoded to return an instance of a `Link`):
```cs
public class LinkConverter : TypeConverter
{
    public override bool CanConvertFrom(ITypeDescriptorContext context,
        Type sourceType)
    {
        return true;
    }
    
    public override object ConvertFrom(ITypeDescriptorContext context,
        CultureInfo culture, object value)
    {
        return new Link()
        {
            Label = "Hello",
            NewWindow = true,
            Title = "world",
            Url = "/stuff"
        };
    }

}
```

And here's the part of my CSHTML file in which I get the content to render:
```cs
var page = Model.Content.As<TypicalPage>();
var widgets = page.MainContent;
// ...here I render out the widgets...
```

Note that I can actually get the type converter to run if I change my `Callout` class so the `Link` property has an `ArchetypeValueResolver` that points to another property alias that exists:
```cs
[TypeConverter(typeof(LinkConverter))]
[ArchetypeValueResolver(alias: "summary")]
public Link Link { get; set; }
```

Of course, that is not a real solution, as my type converter needs to have the data from the correct property.

FYI, I dug into the `umbraco.config` file to get the value of the published Archetype property, which looks like this:

```json
{
   "fieldsets":[
      {
         "properties":[
            {
               "alias":"summary",
               "value":"<p>This is the <strong>summary</strong> text.</p>"
            },
            {
               "alias":"header",
               "value":"Ready to Enroll?"
            },
            {
               "alias":"link",
               "value":"{\"fieldsets\":[{\"properties\":[{\"alias\":\"linkLabel\",\"value\":\"Home\"},{\"alias\":\"linkSuffix\",\"value\":\"?source=callout\"},{\"alias\":\"linkTitle\",\"value\":\"The Home Page\"},{\"alias\":\"linkPage\",\"value\":\"1072\"},{\"alias\":\"newWindow\",\"value\":\"[{\\\"key\\\":\\\"True\\\",\\\"label\\\":\\\"Open in New Window\\\"}]\"}],\"alias\":\"contentLink\",\"disabled\":false,\"id\":\"e1645244-46a3-41ae-bccb-9d07dbf7cb24\"}]}"
            }
         ],
         "alias":"callout",
         "disabled":false,
         "id":"7e02489f-c165-4d43-8b6b-9d8b80c3d488"
      }
   ]
}
```

You can see that the `link` property does exist and has a value.

**Comment by micklaw** [comment]
Nicolas, 

If you check the sample project in the github repo, I have the exact same setup working which you describe here. I think your issue here is in the Json, I think your link archetype is called 'contentLink'?

Also, you shouldn't have to use a TypeConverter at all. The archetypevalueresolver is what you want here on the link property. Plus you don't need to specify the alias as the property name matches the umbraco property.

Think it's just your archetype alias for link that's messing you up dude. Ditching the TyprConverter on the link property and adding an archetypecontent ("contentLink") to your link class should sort it.

**Comment by Nicholas-Westby** [comment]
Could you send me a link to the sample project where it's doing what I'm doing?

> I think your issue here is in the Json, I think your link archetype is called 'contentLink'?

Could you clarify that question? I have an Archetype fieldset with an alias of `contentLink`, if that's what you mean.

I actually need to do a type converter because links are more complicated than they seem. There are actually 4 possible links: content link, media link, external link, and overlay link (they all have different properties that need some massaging before I can create a proper `Link` instance). And I've found that TypedMedia is too slow for fetching hundreds of media URL's on a page, so I have those cached and use the cache during mapping operations.

The `Link` class should not need an `ArchetypeContent` attribute, as I'm using a type converter (i.e., I will be handling all the conversion, so Ditto Resolvers does not need to know about the particulars of the data).

By the way, my code has been through many iterations before I posted. I had created a version without specifying the alias for properties which matched the alias of the data. I had just specified the alias to see if there was some subtle bug that required it.

I'll give the `ArchetypeContent` attribute a try tomorrow, but I'm pretty sure I already tried that (or some variation of that).

**Comment by micklaw** [comment]
Hey Nicholas,

Here is a link to the sample project:

https://github.com/micklaw/Ditto.Resolvers/tree/dev/Ditto.Resolvers.Sample

The issue your having is with your use of a TypeConverter on your POCO for a field which is an ArchetypeFieldsetModel on the IPublishedContent. If the code finds an ArchetypeFieldsetModel it treats it as expecting to bind a new Archetype POCO, so therefore the TypeCoverter would be ignored as the property is an Archetype. As you are trying to use a TypeConverter instead this isn't possible with the current functionality. TypeConverters work on all properties where it is not a child Archetype.

The logic for this should be fairly simple to move to only use a property as an archetype if it contains the archetypevalueresolverattribute. I'll do that and give you shout. Think it was only changed in the last commit!

**Comment by micklaw** [comment]
Right that's updated to only treat it as an archetype if the ArchetypeValueResolverAttribute is decorated on the property and the content is of type ArchetypeFieldsetModel on the PublishedContent.

You should be able to update the new -pre to get it.

Cheers

**Comment by Nicholas-Westby** [comment]
I updated to the latest prerelease and removed the `ArchetypeValueResolver` attribute from the `Link` property on the `Callout` class and it seems to work, sort of. Here's what I'm seeing now:

![breakpoint](https://cloud.githubusercontent.com/assets/5933222/12038473/45e3d68a-ae0d-11e5-8441-10210bf5f6ad.png)

I am getting a JSON string rather than an `ArchetypeModel`. This will make parsing a bit more difficult, which is not ideal.

The other problem I'm anticipating is that I was able to specify an Archetype property alias with the `ArchetypeValueResolver` attribute, but now that I'm forced to remove that attribute from my nested Archetype properties that require a type converter, I will be unable to use a property name that differs from the Archetype property alias. That could get me into some weird scenarios, such as when I happen to name my class with the same name as a property (C# doesn't allow that). Some contrived examples would be a rich text widget with a rich text property or a link widget with a link property.

Any chance of getting either of those issues fixed?

**Comment by Nicholas-Westby** [comment]
Here's my temporary workaround for one of those two issues:

```cs
if (value is string)
{
    value = JsonConvert.DeserializeObject<ArchetypeModel>(value as string);
}
```

That is, if value is a string, I deserialize it into an `ArchetypeModel`. Not ideal, but works.

**Comment by micklaw** [comment]
Nicholas,

The issue you mentioned above isn't actually anything to do with the resolvers code, but is just how umbraco stores an ArchetypeModel in the DB and config. So when you get a property value, you get a string, I'm pretty certain to get an strong archetype model you need to do node.getProperty<ArchetypeModel> so your 'workaround' is the recommended solution in this case.

In regards to the alias issue. I might add an ArchetypePropertyAttribute too for this case. I swayed on whether to do this originally, but now it seems it has a case to be seperate as the ArchetypeValueResolverAttribute is breaking the single responsibility rule in my eyes.

**Comment by micklaw** [comment]
Above should be:

node.getProperty&lt;ArchetypeModel&gt;

Sorry, using a phone just now.

**Comment by Nicholas-Westby** [comment]
That makes some sense that I'll have to deal with the JSON, so it's not a deal breaker for me.

And I'll be happy to test the new attribute for aliasing purposes.

Thanks for all the help :+1:

**Comment by micklaw** [comment]
Hey Nicholas,

I've added the **ArchetypePropertyAttribute** now. The README has been updated to show how to use it, long and short of it is, its like this:

```csharp
	public class PriceList : IFieldset
    {
        ...

        [ArchetypePropertyAttribute("randomAlias")]
        public string Price { get; set; }
    }
```
You can still use the **ArchetypeValueResolverAttribute** if its a child Archetype and specify an alias on it. Though if you specify the **ArchetypePropertyAttribute** alias it will override the **ArchetypeValueResolverAttribute**  one.

Note, I have done some pretty large scale refactoring to allow for easier unit testing, amended the build and nuget process and integrated the Grid project in to the base resolvers project.

I have streamlined nuget to only include the assemblies now and have now taken the releases out of -pre, and made a full release. Doing **Install-Package Ditto.Resolvers.Archetype** should now install 1.0.1.

Look forward to hearing your results and hopefully, if OK, I'll close this issue.

**Comment by Nicholas-Westby** [comment]
Nice! I'll give it a try when I'm back to work on Monday.

In the meantime, I thought it might be worth mentioning that your appveyor.yml file appears to contain credentials of some sort. I'm not sure what the implications might be, but you may want to consider removing those credentials from Git and changing them in case they can be abused (e.g., by some malicious developer). Maybe they can't be abused, but thought I'd mention it just in case.

**Comment by micklaw** [comment]
It's cool, I have encrypted them with then AppVeyor encryption page. So not to worry. =)

**Comment by Nicholas-Westby** [comment]
FYI, I updated to the latest version and the new `ArchetypeProperty` attribute worked perfectly. This issue can be closed. Thanks!

**Comment by micklaw** [comment]
Awesome. Thanks Nicholas. Any others features you fancy or think maybe of use please throw them on.
