### ISSUE TITLE
Use Archetype.Binaries NuGet Dependency

### ISSUE THREAD

**Issue by Nicholas-Westby** [micklaw/Ditto.Resolvers#6]
Looks like Kevin just split Archetype into the main package and a package containing only the binaries: https://www.nuget.org/packages/Archetype.Binaries

See issue here: https://github.com/imulus/Archetype/issues/312

Now would be a good time to test if you can modify your package to have a dependency on Archetype.Binaries rather than Archetype.

**Comment by micklaw** [comment]
I've update this now dude, the nuget page isn't showing the update though, but the nuspec when you download it has the binaries referenced. So should be all good.

**Comment by Nicholas-Westby** [comment]
Didn't seem to work for me. When I updated (via the update tab in Visual Studio), it installed the full Archetype package rather than the Archetype.Binaries package (e.g., it created an `App_Plugins/Archetype` folder in my class library).

**Comment by micklaw** [comment]
yeah weird me too, just fixing now

On 6 January 2016 at 23:13, Nicholas-Westby <notifications@github.com>
wrote:

> Didn't seem to work for me. When I updated (via the update tab in Visual
> Studio), it installed the full Archetype package rather than the
> Archetype.Binaries package (e.g., it created an App_Plugins/Archetype
> folder in my class library).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/micklaw/Ditto.Resolvers/issues/6#issuecomment-169492162>
> .
>



-- 

Cheers

Michael Law

**Comment by Nicholas-Westby** [comment]
FYI, here's what I see when I go to https://www.nuget.org/packages/Ditto.Resolvers.Archetype/1.0.2

![dependencies](https://cloud.githubusercontent.com/assets/5933222/12157704/7dc13512-b488-11e5-9dab-26e929be5602.png)

Note that it depends on Archetype rather than Archetype.Binaries.

**Comment by micklaw** [comment]
Ah, I messed up originally and it appears you can't overwrite a nuget package when i redone 1.0.2.

1.0.3 should have sorted it.

**Comment by Nicholas-Westby** [comment]
Strangely, I get this error:

![error](https://cloud.githubusercontent.com/assets/5933222/12158085/9f95cf1a-b48b-11e5-91a2-5f91e6acecdc.png)

When I attempt to click the "Install" button (1.0.3 is the item selected in the drop down):

![install-button](https://cloud.githubusercontent.com/assets/5933222/12158134/f772960a-b48b-11e5-9b4b-285a3f6fbfc8.png)

Perhaps I need to wait a bit for some caches to update or something.

**Comment by micklaw** [comment]
I think this is because i removed the 1.0.2 package. I re-added i there,
try now.


On 6 January 2016 at 23:42, Nicholas-Westby <notifications@github.com>
wrote:

> Strangely, I get this error:
>
> [image: error]
> <https://cloud.githubusercontent.com/assets/5933222/12158085/9f95cf1a-b48b-11e5-91a2-5f91e6acecdc.png>
>
> When I attempt to click the "Install" button (1.0.3 is the item selected
> in the drop down):
>
> [image: install-button]
> <https://cloud.githubusercontent.com/assets/5933222/12158134/f772960a-b48b-11e5-9b4b-285a3f6fbfc8.png>
>
> Perhaps I need to wait a bit for some caches to update or something.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/micklaw/Ditto.Resolvers/issues/6#issuecomment-169499215>
> .
>



-- 

Cheers

Michael Law

**Comment by Nicholas-Westby** [comment]
Sweet! Seemed to update just fine now. Thanks :+1:

**Comment by micklaw** [comment]
Awesome, Ill close this off
