### ISSUE TITLE
Value Resolvers Don't Work

### ISSUE THREAD

**Issue by Nicholas-Westby** [micklaw/Ditto.Resolvers#7]
In short, this is what I have (works, but is clumsy):

```cs
[ArchetypeContent(alias: "graphicalBanner")]
public class GraphicalBanner : IWidget
{
    // Random property so that Ditto knows to map it.
    [ArchetypeProperty(alias: "labelIgnored")]
    [TypeConverter(typeof(BreadcrumbConverter))]
    public List<Link> Breadcrumbs { get; set; }
}
```

And this is what I want to do (does not work, but I want it to):

```cs
[ArchetypeContent(alias: "graphicalBanner")]
public class GraphicalBanner : IWidget
{
    [DittoValueResolver(typeof(BreadcrumbResolver))]
    public List<Link> Breadcrumbs { get; set; }
}
```

Basically, I'm mapping a graphical banner, which has an image, a title, and a breadcrumb. The tricky bit is that the breadcrumb is not specified on the graphical banner Archetype. Instead, it is constructed by creating links out of the current page the Archetype widget is used on and all of that page's ancestors.

I was able to get this working using a `TypeConverter` (as shown above). The problem is that in order for the type converter to run, it needs to be based off of an Archetype property, even if that property isn't actually used in the type conversion. My workaround was to assign an arbitrary property (i.e., one completely unrelated to the breadcrumb) as the one to map (in this case, it was "labelIgnored"). That's a little silly that I have to pass an unrelated property to a type converter in order to get it to work.

What I'm hoping is that you can get value resolvers to work (the assumption being that value resolvers don't need to be based on an Archetype property). I tried a value resolver (as shown above), but the code was never called.

As a side note, I believe the Ditto team is thinking of adding a new concept of "processors". I only vaguely remember hearing something about it, but i think the idea is that a processor would replace both concepts of type converters and value resolvers. Don't quote me on that, but it's food for thought in case you want to go down a similar path.

**Comment by micklaw** [comment]
Hey Nicholas

Thanks for this. 

Initially when I built this little library it only really ever resolved Archetypes and TypeConverters. That's all I ever really needed Ditto to do at that stage, but obviously with its evolution,  I've had to amend some parts of this too (not for the better in some occasions). For example, the guys done some refactoring around the Binding of a property on a POCO to make some methods private. Unfortunately it meant I had to use reflection to hook in to this method (not ideal). The point I'm making is I'll need to check if the methods for hooking in this functionality are available to us. Hopefully they will be.

So as I say, in this instance I'll need to check to see if the binding of the new Processor functionality and binding of ValueResolvers can be easily hooked too. I'm sure I seen the guys discussing whether chained processors would actually just take over from both TypeConverters and ValueResolvers eventually maybe @leekelleher or @mattbrailsford could given us some insight as to what direction they see Ditto moving in this regard?

I'll probably hold off making this change until it's a little clearer what their desired approach will be. Though I'll defo take a look in to the existing source and if it's trivial to add temporarily I will add this amend in.

Thanks again Nicholas.

**Comment by leekelleher** [comment]
Yes, in upcoming Ditto v0.9.0, both TypeConverters and ValueResolvers have been superseded by Processors, ([see Ditto issue #143 for the full discussion](https://github.com/leekelleher/umbraco-ditto/pull/143)).  *This is still under development and still to be properly documented.* (We don't have a scheduled release date for v0.9.0 yet. Sorry for any headaches this may cause)

**Comment by micklaw** [comment]
Not a problem and thanks for getting back to us. 

For what its worth, I'd be glad to see Ditto run with just processors and loose the ValueResolver / TypeConverter crossover, but I suppose backwards compatibility is an issue for folks then its good to keep supporting them.

**Comment by micklaw** [comment]
Nicholas,

I have added some amends to hook in to both methods now used by Ditto, the first is for getting ValueResolver conversions and the second for getting TypeConverter conversions. Now when you are getting properties of an Archetype you can use ValueResolvers or TypeConvertrs as per Ditto. You'll still be required to use an **ArchetypePropertyAttribute** if your aliases are different though.

Hope it works out OK for you.

Michael

**Comment by micklaw** [comment]
Here's a version of the alpha, so you don't need to go digging. I should set up MyGet.

[Ditto.Resolvers.Archetype.1.0.3-alpha-000121.zip](https://github.com/micklaw/Ditto.Resolvers/files/92652/Ditto.Resolvers.Archetype.1.0.3-alpha-000121.zip)

**Comment by Nicholas-Westby** [comment]
I'll give that a go on Monday. Thanks!

**Comment by Nicholas-Westby** [comment]
I was trying to test this out, but after I upgraded, I got this a `TargetInvocationException` without making any code changes (the message was `Exception has been thrown by the target of an invocation.`):

```
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Our.Umbraco.Ditto.Resolvers.Shared.Services.DittoValueService.Set(IPublishedContent content, CultureInfo culture, PropertyInfo propertyInfo, Object propertyValue, Object instance, DittoValueResolverContext context)
   at Our.Umbraco.Ditto.Resolvers.Archetype.Services.ArchetypeBindingService.GetTypedArchetype(ArchetypeModel archetype, Type entityType, CultureInfo culture, IPublishedContent content, DittoValueResolverContext context)
   at Our.Umbraco.Ditto.Resolvers.Archetype.Services.ArchetypeBindingService.As(ArchetypeModel archetype, Type type, CultureInfo culture, IPublishedContent content, DittoValueResolverContext context)
   at Our.Umbraco.Ditto.Resolvers.Archetype.Resolvers.ArchetypeValueResolver.ResolveValue()
   at Our.Umbraco.Ditto.DittoValueResolver`2.ResolveValue(DittoValueResolverContext context, DittoValueResolverAttribute attribute, CultureInfo culture)
   at Our.Umbraco.Ditto.PublishedContentExtensions.GetResolvedValue(IPublishedContent content, CultureInfo culture, PropertyInfo propertyInfo, Object instance, IEnumerable`1 valueResolverContexts)
   at Our.Umbraco.Ditto.PublishedContentExtensions.ConvertContent(IPublishedContent content, Type type, CultureInfo culture, Object instance, IEnumerable`1 valueResolverContexts, Action`1 onConverting, Action`1 onConverted)
   at Our.Umbraco.Ditto.PublishedContentExtensions.As(IPublishedContent content, Type type, CultureInfo culture, Object instance, IEnumerable`1 valueResolverContexts, Action`1 onConverting, Action`1 onConverted)
   at Our.Umbraco.Ditto.CurrentContentAsValueResolver.ResolveValue()
   at Our.Umbraco.Ditto.DittoValueResolver`2.ResolveValue(DittoValueResolverContext context, DittoValueResolverAttribute attribute, CultureInfo culture)
   at Our.Umbraco.Ditto.PublishedContentExtensions.GetResolvedValue(IPublishedContent content, CultureInfo culture, PropertyInfo propertyInfo, Object instance, IEnumerable`1 valueResolverContexts)
   at Our.Umbraco.Ditto.PublishedContentExtensions.ConvertContent(IPublishedContent content, Type type, CultureInfo culture, Object instance, IEnumerable`1 valueResolverContexts, Action`1 onConverting, Action`1 onConverted)
   at Our.Umbraco.Ditto.PublishedContentExtensions.As(IPublishedContent content, Type type, CultureInfo culture, Object instance, IEnumerable`1 valueResolverContexts, Action`1 onConverting, Action`1 onConverted)
   at Our.Umbraco.Ditto.PublishedContentExtensions.As[T](IPublishedContent content, CultureInfo culture, T instance, IEnumerable`1 valueResolverContexts, Action`1 onConverting, Action`1 onConverted)
   at ASP._Page_Views_Typical_cshtml.Execute() in c:\r\MySite\src\MySite.Website\Views\Typical.cshtml:line 7
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance)
   at System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer)
   at Umbraco.Core.Profiling.ProfilingView.Render(ViewContext viewContext, TextWriter writer)
   at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
```

The inner exception was a `NullReferenceException` with a message of `Object reference not set to an instance of an object.` and the following stack trace:

```
   at Our.Umbraco.Ditto.Resolvers.Archetype.Resolvers.ArchetypeValueResolver.ResolveValue()
   at Our.Umbraco.Ditto.DittoValueResolver`2.ResolveValue(DittoValueResolverContext context, DittoValueResolverAttribute attribute, CultureInfo culture)
   at Our.Umbraco.Ditto.PublishedContentExtensions.GetResolvedValue(IPublishedContent content, CultureInfo culture, PropertyInfo propertyInfo, Object instance, IEnumerable`1 valueResolverContexts)
```

Here is line 7 of my CSHTML:

```
var page = Model.Content.As<TypicalPage>();
```

Here's what the `TypicalPage` class looks like:

```
using Compositions;
using Our.Umbraco.Ditto;

public class TypicalPage
{
    [CurrentContentAs()]
    public SEO SEO { get; set; }

    [CurrentContentAs()]
    public Typical Typical { get; set; }
}
```

And here's what my `Typical` class looks like:

```
using Our.Umbraco.Ditto.Resolvers.Archetype.Attributes;
using System.Collections.Generic;
using System.Linq;
using Widgets;

public class Typical
{
    private List<IWidget> mainContent;

    [ArchetypeValueResolver(alias: "mainContent")]
    public List<IWidget> MainContent
    {
        get
        {
            return mainContent ?? new List<IWidget>();
        }
        set
        {

            // Clean data before setting it.
            if (value == null)
            {
                value = new List<IWidget>();
            }
            mainContent = value
                // Skip null items.
                .Where(x => x != null)
                // Skip callouts without links.
                .Where(x => x is ButtonCallout ? (x as ButtonCallout).ButtonLink != null : true)
                .Where(x => x is LinkSidebarCallouts ? (x as LinkSidebarCallouts).Callouts.Any() : true)
                .ToList();

        }
    }

}
```

When I set a breakpoint, none of the code in the getter or setter is called (i.e., the mapping doesn't make it that far). The error doesn't happen unless I have a widget on my content. If I add a rich text widget, for example, I then get the error. Here's what my rich text widget class looks like:

```
using Our.Umbraco.Ditto.Resolvers.Archetype.Attributes;

[ArchetypeContent(alias: "richText")]
public class RichText : IWidget
{
    [ArchetypeValueResolver(alias:"richText")]
    public string Text { get; set; }
}
```

By the way, bravo on this commit :-)

![commit](https://cloud.githubusercontent.com/assets/5933222/12407242/2da13a38-be0a-11e5-9e35-244f25fd649d.png)

**Comment by micklaw** [comment]
Ha, yeah, what a Douche!

I added a sample to the project for this and it seemed to work. From that error it looked to me like when its trying to reflect the private Ditto methods we use, it failing.

Those methods are obviously private for a reason, but I find them really useful. It would be great if the guys could maybe abstract these to their own service and maybe make them protected so I could override them. Might even help with their unit testing.

If you could maybe let me know which version of Ditto you're using (the sample uses 0.8.2) I can check to see if its the correct version that has these methods required.

Have a look at the sample project in the dev branch to confirm I have setup my Integration test the same way yours is setup above.

**Comment by leekelleher** [comment]
@micklaw Which private methods? (sorry, I haven't dug into your code)
I don't want to side-track this thread with details, so if you want to open an issue on the Ditto repo, we can chat on there?

**Comment by micklaw** [comment]
Hey @leekelleher, there are two methods on the **PublishedContentExtensions**, one is called **GetResolvedValue** and the other is **GetConvertedValue**. I think the first is used to get the ValueResolver result and the other for TypeConverters, in the Ditto source (0.8.2) the second seems to be called directly after the first.

I use these to get the values of properties on Archetype POCO which use Ditto attributes. Seems to work alright, though clearly not best practice, but its cool to fly to close to the sun.

**Comment by Nicholas-Westby** [comment]
@micklaw I'm using Ditto 0.8.4 (currently, the latest version).

**Comment by Nicholas-Westby** [comment]
@micklaw FYI, when I downgrade to Ditto 0.8.2, I have the same issue.

**Comment by micklaw** [comment]
Hey @Nicholas-Westby, it seems no matter how I attempt to break this, or what I throw at it, it still seems to bind fine in my sample solution.

I copied exactly as your classes are setup, I fully expected this to break as I haven't  tested anything using the **CurrentContentAsAtttribute** ( didn't even know this was a thing!), but it still binded. Also, I put custom code in the getter and setter, it executed this fine too.

The only thing I can think of is that you have defined an **ArchetypeValueResolverAttribute'** on a property which is an Archetype, but for some reason is attempting to bind to a **string**. This seems like odd behaviour to me and should more than likely be either a custom **ValueResolver** or **TypeConverter**, and the property should be decorated with an **ArchetypePropertyAttribute**.

```csharp
using Our.Umbraco.Ditto.Resolvers.Archetype.Attributes;

[ArchetypeContent(alias: "richText")]
public class RichText : IWidget
{
    [ArchetypeValueResolver(alias:"richText")]
    public string Text { get; set; }
}
```

Below are the classes I setup for my tests. I also updated to use Ditto 0.8.4, though the code worked fine on 0.8.2 also.

##### Main Ditto Page

```csharp
    public class TypicalPage
    {
        [CurrentContentAs]
        public Typical Typical { get; set; }
    }
```

##### Composition

```csharp
    public class Typical
    {
        private List<IWidget> _priceList { get; set; }

        [ArchetypeValueResolver("priceList")]
        public List<IWidget> PriceList
        {
            get
            {
                return _priceList ?? new List<IWidget>();
            }
            set
            {
                if (value == null)
                {
                    value = new List<IWidget>();
                }

                _priceList = value.Take(1).ToList();
            }
        }
    }
```

##### Archetype

```csharp
    public interface IWidget
    {
    }

    [ArchetypeContent(alias: "priceList")]
    public class PriceList : IWidget, IFieldset
    {
        public string Title { get; set; }

        public int Quantity { get; set; }

        public string Price { get; set; }

        [TypeConverter(typeof(DittoPickerConverter))]
        public Content AssociatedPage { get; set; }

        public string Alias { get; set; }

        public bool Disabled { get; set; }

        [ArchetypeProperty("randomAlias")]
        public string AnotherText { get; set; }

        public string TestStringField { get; set; }

        IEnumerable<GabeHCoud> _persons { get; set; }

        [DittoValueResolver(typeof(GabeHCoudResolvers))]
        public IEnumerable<GabeHCoud> Persons
        {
            get
            {
                return _persons ?? new List<GabeHCoud>();
            }
            set
            {
                if (value == null)
                {
                    value = new List<GabeHCoud>();
                }

                _persons = value.Take(1).ToList();
            }
        }
    }
```

##### This is all called in the usual manner:

```csharp
        public override ActionResult Index(RenderModel model)
        {
            var viewModel = new ViewModel<Home>
            {
                Content = model.As<Home>()
            };

            var poco = model.As<TypicalPage>();

            return CurrentTemplate(viewModel);
        }
```

**Comment by Nicholas-Westby** [comment]
Will try to create a sample GitHub repo for you soon. Busy with work at the moment.

**Comment by Nicholas-Westby** [comment]
@micklaw I created a repository that demonstrates the issue so you can reproduce it: https://github.com/Nicholas-Westby/ditto-resolver-invoke-error

Simply build in Visual Studio 2013 (which should run NuGet package restore, which means you'll need to have your above-linked prerelease package available from a package source) and view the homepage. You should get the exception:

![error](https://cloud.githubusercontent.com/assets/5933222/12533529/c9d873aa-c1e6-11e5-80be-9008ec053a84.png)

By the way, you'll notice a few extra commits in the repo. Umbraco kept deleting my content for some reason. Not sure what's up with that. Perhaps some bug related to Umbraco when used with SQL Server CE. If you run into that issue, you can create a home node that looks like this:

![home](https://cloud.githubusercontent.com/assets/5933222/12533532/34d1b4d2-c1e7-11e5-8d5c-37e9989435bf.png)

All of the code (aside from the CSHTML) is in the Demo.App project. It's just a few files, so should be easy enough to sort through.

**Comment by micklaw** [comment]
Hey Nicholas,

I had a gander on the repository you put up and it was as I suspected in my last comment. Basically your 'mainContent' Archetype is setup like so:

```json
{"fieldsets":[{"properties":[{"alias":"text","value":"<p>Some sample content.</p>"}],"alias":"richText","disabled":false,"id":"33f1ebd5-5f7a-44c2-8b3d-d47042444a2e"}]}
```

You'll notice that you have the 'text' property (defined as what I'm assuming is an RTE in the CMS?) in your RichTextWidget POCO decorated with another ArchetypeValueResolverAttribute, though in the the related fieldset for this above this is clearly not a child Archetype of RichTextWidget, so therefore was blowing up. I have added some validation to cover this now, so you should get a nicer exception detailing that if you are using an ArchetypeResolverAttribute on a property which is not an Archetype, it will throw an Exception.

```csharp
[ArchetypeContent(alias: "richText")]
public class RichText : IWidget
{
    [TypeConverter(typeof(DittoHtmlStringConverter))]
    public IHtmlStringText { get; set; }
}
```

Simply removing the line or changing it to use a TypeConverter fixed the issue for me.

Cheers

**Comment by Nicholas-Westby** [comment]
Thanks for looking into that. I will try with my main repo at work on Monday.

By the way, I think I forgot to mention the Umbraco login credentials for the repo I sent you. The username is "admin" and the password is "adminadmin". Not that you'll need them now, but in case you need to poke around again.

**Comment by micklaw** [comment]
[Ditto.Resolvers.Archetype.1.0.3-alpha-000125.zip](https://github.com/micklaw/Ditto.Resolvers/files/102622/Ditto.Resolvers.Archetype.1.0.3-alpha-000125.zip)

**Comment by Nicholas-Westby** [comment]
Seems like it's mostly working. Here's my class:

```cs
// Namespaces.
using Converters;
using Our.Umbraco.Ditto;
using Our.Umbraco.Ditto.Resolvers.Archetype.Attributes;
using System.Collections.Generic;
using System.ComponentModel;
using Types;
using ValueResolvers;


/// <summary>
/// The graphical banner widget.
/// </summary>
[ArchetypeContent(alias: "graphicalBanner")]
public class GraphicalBanner: IWidget
{

    #region Properties

    /// <summary>
    /// The banner's header.
    /// </summary>
    [TypeConverter(typeof(HeaderConverter))]
    public string Header { get; set; }


    /// <summary>
    /// The banner's breadcrumbs.
    /// </summary>
    [DittoValueResolver(typeof(BreadcrumbValueResolver))]
    public List<Link> Breadcrumbs { get; set; }

    #endregion

}
```

This actually works for my breadcrumbs example. However, it still isn't working quite as I'd expect. Take a look at this breakpoint to understand why:

![breakpoint](https://cloud.githubusercontent.com/assets/5933222/12601344/38fe22fa-c455-11e5-98af-51474d5c160d.png)

I am looking at the value of `this`, which contains contextual information I can use to resolve a value. Trouble is, I don't see the current Archetype anywhere in there. I see the current node, but that's the context that wraps the current Archetype context. What I'd expect to see would be the Archetype for the graphical banner. When I looked at `this.Context.Instance`, it again contained the current content node rather than an Archetype fieldset.

I'll take a look at this other issue to see if it has some sort of context information about the current Archetype fieldset: https://github.com/micklaw/Ditto.Resolvers/issues/10 If so, I may be able to use that rather than a value resolver for cases where I need the current Archetype being mapped.

**Comment by micklaw** [comment]
Hi Nicholas, this feels like a seperate issue to me from the original request. 

As this is effectively piggy backing Ditto, it is the Ditto context that you are getting, It wouldn't be possible for me to inject the current ArchetypeFieldsetModel in here without effectively rebuilding the resolvers in some way to mimic Ditto functionality. 

It would be possible as you say to inject the ArchetypeFieldsetModel in to the OnConvert methods if that helps?

**Comment by micklaw** [comment]
I'll close this issue as the original request is complete and raise a new one for the context request amend.

Cheers

**Comment by Nicholas-Westby** [comment]
Makes sense. Thanks!
